version: '{build}'
os: Visual Studio 2015
clone_depth: 1

configuration:
- Release

before_build:
- cmake -H. -Bbuild -G"Visual Studio 14 2015 Win64"

build_script:
- cmake --build build --config Release
